/**
 * Professional ATS-Optimized Resume Templates Configuration
 */
export const TEMPLATES = [
  {
    id: "classic",
    name: "Classic Corporate",
    badge: "Most Popular",
    atsScore: "99%",
    atsLabel: "Excellent",
    description: "Time-tested standard format with elegant typography loved by Fortune 500 recruiters and corporate employers.",
    preview: "Traditional centered header with clean divider and balanced serif/sans typography",
    bestFor: "Finance, Banking, Consulting, Law, Corporate Roles",
    accent: "#1E3A8A",
    features: ["Chronological Hierarchy", "Refined Divider", "Maximum ATS Parsing"],
  },
  {
    id: "skill-bullet",
    name: "Skill Bullet Matrix",
    badge: "New",
    atsScore: "100%",
    atsLabel: "Ultimate",
    description: "Specialized layout displaying technical skills in clean vertical bullet points for maximum recruiter clarity and ATS match rate.",
    preview: "Vertical bulleted skill competencies with sleek section dividers and clear typography",
    bestFor: "Developers, IT Professionals, Engineers, Analysts, Specialists",
    accent: "#10B981",
    features: ["Vertical Bullet Skills", "High-Contrast Hierarchy", "100% ATS-Friendly"],
  },
  {
    id: "modern",
    name: "Modern Tech",
    badge: "Trending",
    atsScore: "98%",
    atsLabel: "High",
    description: "Contemporary tech-focused layout with sleek left-aligned header, timeline markers, and structured project cards.",
    preview: "Contemporary left-aligned header with timeline dot accents and skill pill tags",
    bestFor: "Software Engineers, Product Managers, Data Scientists, Tech Leads",
    accent: "#4F46E5",
    features: ["Tech Timeline Dots", "Structured Project Cards", "Dynamic Skill Pills"],
  },
  {
    id: "minimal",
    name: "ATS Pro Minimal",
    badge: "100% ATS",
    atsScore: "100%",
    atsLabel: "Ultimate",
    description: "Ultra-clean Scandinavian minimalism with maximum whitespace, high-contrast text, and zero parsing obstacles.",
    preview: "Pure minimalist layout with wide-tracked headings and high readability",
    bestFor: "All Industries, Corporate, Healthcare, Academic, Job Portals",
    accent: "#0D9488",
    features: ["Zero Visual Clutter", "Ultra-High Readability", "100% Machine Parsable"],
  },
  {
    id: "executive",
    name: "Executive Leadership",
    badge: "Senior Level",
    atsScore: "99%",
    atsLabel: "Excellent",
    description: "Distinguished executive format with prominent leadership title block, summary highlight container, and bold impact metrics.",
    preview: "Authoritative letterhead with executive summary callout and strategic focus",
    bestFor: "C-Suite, VPs, Directors, Senior Managers, Board Members",
    accent: "#7C3AED",
    features: ["Executive Summary Callout", "Strategic Initiatives Focus", "Dignified Serif Hierarchy"],
  },
  {
    id: "boardroom",
    name: "Technical / Engineering",
    badge: "Developer",
    atsScore: "99%",
    atsLabel: "Excellent",
    description: "Engineering-focused layout highlighting technical stacks, GitHub/Live links, measurable metrics, and categorized skills.",
    preview: "Engineering layout with tech stacks, project impact points, and core competencies",
    bestFor: "Full Stack Developers, DevOps, Cloud Architects, QA Engineers",
    accent: "#0F766E",
    features: ["Tech Stack Tags", "Metric-Driven Bullets", "Categorized Competencies"],
  },
  {
    id: "minimal-image",
    name: "Compact Professional",
    badge: "Photo / Split",
    atsScore: "96%",
    atsLabel: "Great",
    description: "Modern split layout with optional profile avatar, structured contact sidebar, and clean expansive main content column.",
    preview: "Clean split format with profile avatar support and structured contact sidebar",
    bestFor: "UI/UX Designers, Marketing, Creative Directors, International Roles",
    accent: "#0284C7",
    features: ["Profile Avatar Support", "Structured Contact Sidebar", "Balanced Two-Column Layout"],
  },
];

export const DEFAULT_TEMPLATE = "classic";
export const DEFAULT_ACCENT_COLOR = "#1E3A8A";
