export const TRACKER_STAGES = [
  {
    id: "wishlist",
    title: "Wishlist",
    icon: "📌",
    color: "bg-slate-100 text-slate-700 border-slate-200",
    badgeColor: "bg-slate-200 text-slate-800",
    headerBg: "bg-slate-100/90 text-slate-800 border-slate-200",
    accentGlow: "from-slate-400/20 to-slate-200/5",
    dotColor: "bg-slate-400",
  },
  {
    id: "applied",
    title: "Applied",
    icon: "🚀",
    color: "bg-blue-50 text-blue-700 border-blue-200",
    badgeColor: "bg-blue-100 text-blue-800",
    headerBg: "bg-blue-50/90 text-blue-800 border-blue-200",
    accentGlow: "from-blue-500/20 to-indigo-500/5",
    dotColor: "bg-blue-500",
  },
  {
    id: "interviewing",
    title: "Interviewing",
    icon: "📞",
    color: "bg-amber-50 text-amber-700 border-amber-200",
    badgeColor: "bg-amber-100 text-amber-800",
    headerBg: "bg-amber-50/90 text-amber-800 border-amber-200",
    accentGlow: "from-amber-500/20 to-orange-500/5",
    dotColor: "bg-amber-500",
  },
  {
    id: "offer",
    title: "Offer Received",
    icon: "🏆",
    color: "bg-emerald-50 text-emerald-800 border-emerald-200",
    badgeColor: "bg-emerald-100 text-emerald-800",
    headerBg: "bg-emerald-50/90 text-emerald-800 border-emerald-200",
    accentGlow: "from-emerald-500/20 to-teal-500/5",
    dotColor: "bg-emerald-500",
  },
  {
    id: "archived",
    title: "Archived",
    icon: "📁",
    color: "bg-slate-100 text-slate-600 border-slate-200",
    badgeColor: "bg-slate-200 text-slate-600",
    headerBg: "bg-slate-100/90 text-slate-600 border-slate-200",
    accentGlow: "from-slate-300/20 to-slate-100/5",
    dotColor: "bg-slate-400",
  },
];

export const PRIORITY_LEVELS = [
  { id: "urgent", label: "Urgent", icon: "🔥", badge: "bg-red-50 text-red-700 border-red-200" },
  { id: "high", label: "High", icon: "⭐", badge: "bg-amber-50 text-amber-700 border-amber-200" },
  { id: "medium", label: "Normal", icon: "📌", badge: "bg-slate-50 text-slate-700 border-slate-200" },
  { id: "low", label: "Low", icon: "💤", badge: "bg-slate-50 text-slate-500 border-slate-200" },
];

export const INTERVIEW_ROUNDS = [
  "Recruiter Screen",
  "Technical Screen",
  "Coding Assessment",
  "System Design",
  "Behavioral / Values",
  "Hiring Manager Round",
  "Executive / Final Round",
  "Offer Negotiation",
];

export const INITIAL_DEMO_APPLICATIONS = [
  {
    id: "app-1",
    company: "Stripe",
    position: "Senior Full Stack Engineer",
    location: "Remote (US/Global)",
    workMode: "Remote",
    salary: "$165k - $190k",
    stage: "interviewing",
    priority: "urgent",
    interviewRound: "System Design",
    interviewDate: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    appliedDate: "2026-08-28",
    followUpDate: "2026-09-06",
    jobUrl: "https://stripe.com/jobs",
    recruiterName: "Sarah Jenkins",
    recruiterEmail: "sjenkins@stripe.com",
    tailoredResume: "Full Stack (Stripe Tailored)",
    notes: "System Design interview scheduled for Friday. Review distributed caching, idempotent payment workflows, and webhook resilience.",
  },
  {
    id: "app-2",
    company: "Vercel",
    position: "Staff Frontend Architect",
    location: "San Francisco, CA (Hybrid)",
    workMode: "Hybrid",
    salary: "$180k - $210k",
    stage: "applied",
    priority: "high",
    interviewRound: "Technical Screen",
    interviewDate: "",
    appliedDate: "2026-09-01",
    followUpDate: new Date(Date.now() + 86400000 * 3).toISOString().split("T")[0],
    jobUrl: "https://vercel.com/careers",
    recruiterName: "Alex Rivera",
    recruiterEmail: "alex.r@vercel.com",
    tailoredResume: "Frontend Architect 2026",
    notes: "Applied with 98% ATS verified tailored resume focusing on React Server Components, Next.js optimization, and Edge rendering.",
  },
  {
    id: "app-3",
    company: "Linear",
    position: "Product Engineer",
    location: "Remote",
    workMode: "Remote",
    salary: "$150k - $175k",
    stage: "offer",
    priority: "urgent",
    interviewRound: "Offer Negotiation",
    interviewDate: "",
    appliedDate: "2026-08-15",
    followUpDate: "2026-09-10",
    jobUrl: "https://linear.app/jobs",
    recruiterName: "Elena Rostova",
    recruiterEmail: "elena@linear.app",
    tailoredResume: "Full Stack Master",
    notes: "Received formal written offer! Currently evaluating base salary vs equity package. Need to confirm health benefits.",
  },
  {
    id: "app-4",
    company: "Figma",
    position: "UI Systems Engineer",
    location: "San Francisco, CA (Hybrid)",
    workMode: "Hybrid",
    salary: "$160k - $185k",
    stage: "wishlist",
    priority: "medium",
    interviewRound: "",
    interviewDate: "",
    appliedDate: "",
    followUpDate: "",
    jobUrl: "https://figma.com/careers",
    recruiterName: "Marcus Vance",
    recruiterEmail: "",
    tailoredResume: "",
    notes: "Need to tailor resume with WebGL, WebAssembly, and Canvas architecture keywords before applying.",
  },
];

export const TRACKER_STORAGE_KEY = "froggie_job_applications_v1";

export default {
  TRACKER_STAGES,
  PRIORITY_LEVELS,
  INTERVIEW_ROUNDS,
  INITIAL_DEMO_APPLICATIONS,
  TRACKER_STORAGE_KEY,
};

